# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               "AJ's"
tagline:             'Bits & Bobs'
description:         'Bits & Bobs <br>written by <a href="https://github.com/rerel">AJ</a><br>'
url:                 'http://rerel.github.io'
baseurl:             /
paginate:            1

# About/contact
author:
  name:              Aurélien Lemesle
  url:               https://twitter.com/mrrerel
  email:             lemesle.aurelien@gmail.com

# Custom vars
version:             2.0.0

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
